version: '3.8'
services:
  bot:
    build: .
    container_name: RusCo
    restart: always
    volumes:
      - .:/app
      - ./participants.csv:/app/participants.csv
    environment:
      - PYTHONUNBUFFERED=1